packages:
  - "plugins/strapi-plugin-gh-workflow-trigger-v5"

allowBuilds:
  "@swc/core": false
  better-sqlite3: true
  core-js-pure: false
  esbuild: true
  sharp: false
  unrs-resolver: true

overrides:
  esbuild: "0.25.0"
  lodash: "4.18.1"
  ajv: "8.18.0"
